apiVersion: v1
kind: Service
metadata:
  name: svc-gerenciamento-api
  namespace: default
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: gerenciamento-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
