name: aws-oidc-check
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'develop/hom ou main/prd'
        required: true
        default: hom
        type: choice
        options: [hom, prd]
permissions: {}
jobs:
  authenticate:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    env:
      TARGET_ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Check branch
        run: test "$GITHUB_REF" = "refs/heads/$( [ "$TARGET_ENVIRONMENT" = hom ] && echo develop || echo main )"
      - uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_BASE_ROLE_ARN }}
          allowed-account-ids: '121754142617'
      - run: aws sts get-caller-identity
